[[annotation]]
file = "/home/zmvanw01/ref/beds/gene.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["gene"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/intron.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["intron"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/exon_1.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["exon1"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/exon_2.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["exon2"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/l-part2.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["lPart2"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/heptamer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["heptamer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/nonamer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["nonamer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/spacer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["spacer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/region.bed.gz"
columns = [4] # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["region"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/utr.bed.gz"
columns = [4] # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["UTR"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/constant.bed.gz"
columns = [4] # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["constant"]  # Name(s) for the annotation in the output

